INSERT INTO PET (PET_NAME, PET_TYPE, PET_BREED, WEIGHT, VACCINATED, TRAINING_LEVEL)
VALUES ('Buddy', 'Dog', 'Golden Retriever', 25,true,5);
INSERT INTO PET (PET_NAME, PET_TYPE, PET_BREED, WEIGHT, VACCINATED, TRAINING_LEVEL)
VALUES ('Edgar', 'Dog', 'Golden Retriever', 15,true,2);
INSERT INTO PET (PET_NAME, PET_TYPE, PET_BREED, WEIGHT, VACCINATED, TRAINING_LEVEL)
VALUES ('Goofer', 'Dog', 'Golden Retriever', 10,true,1);
INSERT INTO PET (PET_NAME, PET_TYPE, PET_BREED, WEIGHT, VACCINATED, TRAINING_LEVEL)
VALUES ('Sally', 'Dog', 'Golden Retriever', 30,false,5);
INSERT INTO PET (PET_NAME, PET_TYPE, PET_BREED, WEIGHT, VACCINATED, TRAINING_LEVEL)
VALUES ('Rex', 'Dog', 'Golden Retriever', 30,true,5);
INSERT INTO PET (PET_NAME, PET_TYPE, PET_BREED, WEIGHT, VACCINATED, TRAINING_LEVEL)
VALUES ('Canela', 'Dog', 'Golden Retriever', 26,true,4);
INSERT INTO PET (PET_NAME, PET_TYPE, PET_BREED, WEIGHT, VACCINATED, TRAINING_LEVEL)
VALUES ('Spot', 'Dog', 'Golden Retriever', 20,false,2);
INSERT INTO PET (PET_NAME, PET_TYPE, PET_BREED, WEIGHT, VACCINATED, TRAINING_LEVEL)
VALUES ('Josh', 'Dog', 'Golden Retriever', 21,true,5);
INSERT INTO PET (PET_NAME, PET_TYPE, PET_BREED, WEIGHT, VACCINATED, TRAINING_LEVEL)
VALUES ('Josh', 'Dog', 'Poodle', 21,true,5);
